name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f cicd-lab || true
            cd ~/app
            rm -rf *
            git clone https://github.com/kaleakash/cicd-lab.git .
            docker build -t cicd-lab .
            docker run -d -p 80:3000 --name cicd-lab cicd-lab
